name: Continuous Delivery

on:
  push:
    branches: ['main']
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el proyecto
        uses: actions/checkout@v4
      - name: Instalando java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando gradle
        uses: gradle/gradle-build-action@v2
      - name: Compilando el proyecto build project
        run: |
          chmod +x ./gradlew
          ./gradlew build


